baseurl: /cardiff
permalink: pretty
future: true
markdown: kramdown
paginate: 5
repo: cardiff
github_org: maptime
maptime:
  chapter: MaptimeCardiff
  #twitter: @MaptimeCardiff
  #disqus: YOUR DISQUS USERNAME

gems:
  - jekyll-feed
